# Generated by Django 2.2.6 on 2019-11-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
