# Generated by Django 2.2.6 on 2019-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191124_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='small_desc',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='describe',
            name='desc_name',
            field=models.CharField(choices=[('1st', 'aboutWhat'), ('2nd', 'whatsInThere'), ('3rd', 'concluding')], max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_name',
            field=models.CharField(choices=[('1st', 'aboutWhat'), ('2nd', 'whatsInThere'), ('3rd', 'concluding')], max_length=255),
        ),
    ]
